name: Android Build and Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Get packages
        run: flutter pub get

      - name: Set up Keystore
        run: |
          echo keyPassword=\${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }} > $GITHUB_ENV
          echo storePassword=\${{ secrets.ANDROID_KEYSTORE_PASSWORD }} >> $GITHUB_ENV
          echo keyAlias=\${{ secrets.ANDROID_KEYSTORE_ALIAS }} >> $GITHUB_ENV
          echo storeFile=keystore.jks >> $GITHUB_ENV
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Build Android
        run: flutter build apk --release --split-per-abi

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-artifact
          path: build/app/outputs/flutter-apk/*
