name: Android Build and Artifact
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"
          cache: "gradle"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/sdk
            ~/.gradle/caches
          key: android-sdk-${{ runner.os }}-${{ hashFiles('android/app/build.gradle') }}

      - name: Build APK
        run: flutter build apk --release

      - name: Sign app APK
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: build/app/outputs/flutter-apk/
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - name: Archive arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a
          path: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk

      - name: Archive armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: android-armeabi-v7a
          path: |
            build/app/outputs/flutter-apk/*-armeabi-v7a-release-signed.apk

      - name: Archive x86_64
        uses: actions/upload-artifact@v4
        with:
          name: android-x86_64
          path: |
            build/app/outputs/flutter-apk/*-x86_64-release-signed.apk
