name: Android Build and Artifact

on:
  push:
    branches:
      - change-db
jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Set up Flutter
        run: flutter pub get
      - name: Build with Flutter
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        run: flutter build apk --release --split-per-abi
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/flutter-apk/
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Archive arm64-v8a
        uses: actions/upload-artifact@v2
        with:
          name: android-arm64-v8a
          path: |
            build/app/outputs/flutter-apk/*-arm64-v8a-release-signed.apk
      - name: Archive armeabi-v7a
        uses: actions/upload-artifact@v2
        with:
          name: android-armeabi-v7a
          path: |
            build/app/outputs/flutter-apk/*-armeabi-v7a-release-signed.apk
      - name: Archive x86_64
        uses: actions/upload-artifact@v2
        with:
          name: android-x86_64
          path: |
            build/app/outputs/flutter-apk/*-x86_64-release-signed.apk
