name: Android Build and Artifact

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Set up Flutter
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --release --split-per-abi

      - uses: ilharp/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: build/app/outputs/flutter-apk/
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - uses: jungwinter/split@v2
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedFiles }}
          separator: ":"

      - name: Archive arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a
          path: |
            ${{ steps.signed_files.outputs._0 }}

      - name: Archive armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: android-armeabi-v7a
          path: |
            ${{ steps.signed_files.outputs._1 }}

      - name: Archive x86_64
        uses: actions/upload-artifact@v4
        with:
          name: android-x86_64
          path: |
            ${{ steps.signed_files.outputs._2 }}
